### ISSUE TITLE
Syntax errors out of the box

### ISSUE THREAD

**Issue by natalieorsi** [bitovi/github-actions-angular-to-github-pages#1]
Hi, I'm sure I could be doing something wrong, but when I try to create main.yml with the text I copy from the action instructions, I get `end of the stream or a document separator is expected`. I've tried changing the spacing and indentation in every way I could think of, but this errors:

```
            - name: Deploy Angular to GitHub Pages
  # You may pin to the exact commit or the version.
  # uses: bitovi/github-actions-angular-to-github-pages@a75a3bc81b046cf8af9515e46911c648bbfc6c67
  uses: bitovi/github-actions-angular-to-github-pages@v1.0.0
  with:
    # Specifies if this action should checkout the code
    checkout: # optional, default is true
    # Partially clone against a given filter. Overrides checkout-sparse-checkout if set. maps to actions/checkout inputs.checkout-filter
    checkout-filter: # optional
    # Do a sparse checkout on given patterns. Each pattern should be separated with new lines. maps to actions/checkout inputs.sparse-checkout
    checkout-sparse-checkout: # optional
    # Specifies whether to use cone-mode when doing a sparse checkout. maps to actions/checkout inputs.sparse-checkout-cone-mode
    checkout-sparse-checkout-cone-mode: # optional, default is true
    # Specifies the path of the static assets after building
    path: # optional, default is dist/${{ github.event.repository.name }}/browser
    # Specifies the command to run the installation.
    install_command: # optional, default is npm ci
    # Specifies the command to run after the install command for the build
    build_command: # optional, default is npm run build -- --base-href=/${{ github.event.repository.name }}/
    # Specifies if the action should cache npm dependencies.
    caching: # optional
```

I'd love to follow your instructions, but I'm getting stuck here at just saving the file.

**Comment by LeoDiazL** [comment]
Hi @natalieorsi 

First of all, thanks for opening an issue, and sorry for the delayed answer. 

Try starting with a clean approach first, and move from there. 

Go with this example and see where it takes you. 

```
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: build-publish
        uses: bitovi/github-actions-angular-to-github-pages@v1.0.0
        with:
          path: dist/${{ github.event.repository.name }}
```

Leo
